export interface MarkdownCellInput {
  readonly cell_type: "code" | "markdown" | "raw"
  readonly source: string
}

export interface FormatMarkdownOptions {
  readonly includeOutputs?: boolean | undefined
  readonly wrapOutputsInDetails?: boolean | undefined
  readonly renderCellOutputs?: ((cellIndex: number) => string | undefined) | undefined
}

const renderCell = (
  cell: MarkdownCellInput,
  cellIndex: number,
  options: FormatMarkdownOptions
): string[] => {
  const out: string[] = []
  if (cell.cell_type === "markdown") {
    out.push(cell.source.trim())
  } else if (cell.cell_type === "code") {
    out.push("```python")
    out.push(cell.source.replace(/\n$/, ""))
    out.push("```")
  } else {
    out.push("```")
    out.push(cell.source.replace(/\n$/, ""))
    out.push("```")
  }
  if (
    options.wrapOutputsInDetails &&
    cell.cell_type === "code" &&
    options.renderCellOutputs
  ) {
    const outputsText = options.renderCellOutputs(cellIndex)
    if (outputsText && outputsText !== "(no output)") {
      out.push("")
      out.push("<details>")
      out.push(`<summary>Outputs</summary>`)
      out.push("")
      out.push(outputsText)
      out.push("")
      out.push("</details>")
    }
  }
  out.push("")
  return out
}

export const formatNotebookAsMarkdown = (params: {
  cells: ReadonlyArray<MarkdownCellInput>
  includeOutputs?: boolean | undefined
  wrapOutputsInDetails?: boolean | undefined
  renderCellOutputs?: ((cellIndex: number) => string | undefined) | undefined
}): string => {
  const options: FormatMarkdownOptions = {
    includeOutputs: params.includeOutputs ?? false,
    wrapOutputsInDetails: params.wrapOutputsInDetails ?? false,
    renderCellOutputs: params.renderCellOutputs
  }
  const out: string[] = []
  params.cells.forEach((cell, idx) => {
    out.push(...renderCell(cell, idx, options))
  })
  return out.join("\n").trim() + "\n"
}

export const formatNotebookAsPython = (params: {
  cells: ReadonlyArray<MarkdownCellInput>
  header?: string
}): string => {
  const header = params.header ?? "# Generated by opencode-ipynb"
  const out: string[] = [header, ""]
  for (const cell of params.cells) {
    if (cell.cell_type === "code") {
      out.push("# %%")
      out.push(cell.source.replace(/\n$/, ""))
      out.push("")
    } else {
      const lines = cell.source.split("\n")
      for (const line of lines) {
        out.push(line ? `# ${line}` : "#")
      }
      out.push("")
    }
  }
  return out.join("\n")
}
