export const DEFAULT_MAX_SOURCE_CHARS = 12_000
export const DEFAULT_MAX_OUTPUT_CHARS = 6_000
export const DEFAULT_MAX_INSPECT_CELLS = 200
export const DEFAULT_MAX_TRACEBACK_CHARS = 8_000
export const DEFAULT_MAX_IMAGE_NOTICE_COUNT = 20
export const DEFAULT_MAX_EXPORT_CHARS = 60_000
export const DEFAULT_RUN_TIMEOUT_MS = 120_000
export const DEFAULT_INSPECT_PREVIEW_CHARS = 240
