import { describe, expect, it } from "bun:test"
import { formatNotebookAsMarkdown, formatNotebookAsPython, type MarkdownCellInput } from "../../src/format/diff.js"

const cells: ReadonlyArray<MarkdownCellInput> = [
  { cell_type: "markdown", source: "# Title\n\nIntro." },
  { cell_type: "code", source: "x = 1\nprint(x)" },
  { cell_type: "code", source: "y = 2" }
]

describe("formatNotebookAsMarkdown", () => {
  it("renders the cells without outputs by default", () => {
    const out = formatNotebookAsMarkdown({ cells })
    expect(out).toContain("# Title")
    expect(out).toContain("```python")
    expect(out).toContain("x = 1")
    expect(out).not.toContain("<details>")
  })

  it("does not wrap outputs in <details> when wrapOutputsInDetails is false", () => {
    const out = formatNotebookAsMarkdown({
      cells,
      wrapOutputsInDetails: false,
      renderCellOutputs: () => "1\n2\n3"
    })
    expect(out).not.toContain("<details>")
  })

  it("wraps each code cell's outputs in a <details> block", () => {
    const out = formatNotebookAsMarkdown({
      cells,
      wrapOutputsInDetails: true,
      renderCellOutputs: (idx) => `out for ${idx}`
    })
    expect(out).toContain("<details>")
    expect(out).toContain("</details>")
    expect(out).toContain("out for 1")
    expect(out).toContain("out for 2")
  })

  it("only wraps code cells (not markdown or raw)", () => {
    const out = formatNotebookAsMarkdown({
      cells: [
        { cell_type: "markdown", source: "# Heading" },
        { cell_type: "raw", source: "raw text" }
      ],
      wrapOutputsInDetails: true,
      renderCellOutputs: () => "should not be wrapped"
    })
    expect(out).not.toContain("<details>")
  })

  it("does not add a <details> block when renderCellOutputs returns undefined", () => {
    const out = formatNotebookAsMarkdown({
      cells,
      wrapOutputsInDetails: true,
      renderCellOutputs: () => undefined
    })
    expect(out).not.toContain("<details>")
  })

  it("does not add a <details> block when renderCellOutputs returns '(no output)'", () => {
    const out = formatNotebookAsMarkdown({
      cells,
      wrapOutputsInDetails: true,
      renderCellOutputs: () => "(no output)"
    })
    expect(out).not.toContain("<details>")
  })

  it("includes the renderCellOutputs output inside the <details> block", () => {
    const out = formatNotebookAsMarkdown({
      cells: [{ cell_type: "code", source: "1+1" }],
      wrapOutputsInDetails: true,
      renderCellOutputs: () => "2"
    })
    const start = out.indexOf("<details>")
    const end = out.indexOf("</details>")
    expect(start).toBeGreaterThan(-1)
    expect(end).toBeGreaterThan(start)
    const inner = out.slice(start, end)
    expect(inner).toContain("2")
    expect(inner).toContain("<summary>Outputs</summary>")
  })
})

describe("formatNotebookAsPython", () => {
  it("renders a default header", () => {
    const out = formatNotebookAsPython({ cells })
    expect(out).toContain("# Generated by opencode-ipynb")
  })

  it("respects a custom header", () => {
    const out = formatNotebookAsPython({ cells, header: "# my header" })
    expect(out).toContain("# my header")
    expect(out).not.toContain("# Generated by opencode-ipynb")
  })

  it("marks code cells with '# %%' separators", () => {
    const out = formatNotebookAsPython({ cells })
    expect(out).toContain("# %%")
  })
})
